# List of changes -
# 1. creation of this file with a change of name - copied from .github\workflows\build-example-corne-nice_nano_v2-nice_view.yml
# 2. Updating miryoku_layer_alternatives.h - commenting out all unused layouts.
#   2.1 preferred Thumb key layout - find and replace thumb row assignments for non-flipped layouts.
      # #define MIRYOKU_ALTERNATIVES_TAP_QWERTY \
      # U_NP,              U_NP,              U_LT(U_MEDIA, ESC),U_LT(U_NAV, SPACE),U_LT(U_MOUSE, TAB),U_LT(U_SYM, RET),  U_LT(U_NUM, BSPC), U_LT(U_FUN, DEL),  U_NP,              U_NP
      # U_NP,              U_NP,              U_LT(U_MEDIA, ESC),U_LT(U_NAV, TAB),U_LT(U_MOUSE, BSPC), U_LT(U_SYM, SPACE),U_LT(U_NUM, RET), U_LT(U_FUN, DEL),  U_NP,              U_NP

      # #define MIRYOKU_ALTERNATIVES_TAP_QWERTY \
      # U_NP,              U_NP,              &kp ESC,           &kp SPACE,         &kp TAB,           &kp RET,           &kp BSPC,          &kp DEL,           U_NP,              U_NP
      # U_NP,              U_NP,              &kp ESC,           &kp TAB,          &kp BSPC,           &kp SPACE,         &kp RET,           &kp DEL,           U_NP,              U_NP

      # #define MIRYOKU_ALTERNATIVES_NAV \
      # U_NP,              U_NP,              U_NA,              U_NA,              U_NA,              &kp RET,           &kp BSPC,          &kp DEL,           U_NP,              U_NP
      # U_NP,              U_NP,              U_NA,              U_NA,              U_NA,              &kp SPACE,         &kp RET,           &kp DEL,           U_NP,              U_NP

      # #define MIRYOKU_ALTERNATIVES_FUN \
      # U_NP,              U_NP,              &kp K_APP,         &kp SPACE,         &kp TAB,           U_NA,              U_NA,              U_NA,              U_NP,              U_NP
      # U_NP,              U_NP,              &kp K_APP,         &kp TAB,           &kp BSPC,          U_NA,              U_NA,              U_NA,              U_NP,              U_NP

#   2.2 Mouse button reassignment - swapped btn 1 and 2
      # #define MIRYOKU_ALTERNATIVES_MOUSE \
      # U_NP,              U_NP,              U_NA,              U_NA,              U_NA,              U_BTN2,            U_BTN1,            U_BTN3,            U_NP,              U_NP
      # U_NP,              U_NP,              U_NA,              U_NA,              U_NA,              U_BTN1,            U_BTN2,            U_BTN3,            U_NP,              U_NP

name: 'Build corne nice_nano_v2 nice_view'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view"]'
